version: '3.1'
services:
  voltdb:
    image: voltdb/voltdb-community:latest
    container_name: volt
    ports:
      - 21212:21212
    volumes:
      - ../../schema:/voltdb
    environment:
      - HOST_COUNT=1
