version: '3.1'

services:
  mongo:
    container_name: my_mongo
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
